### ISSUE TITLE
萌新求问求源代码

### ISSUE THREAD

**Issue by Fooler00** [yfismine/GoBang-AI#1]
将大佬您的代码抄下来后在编译器上运行不了，有几个类型和函数在GoBangMaster.hpp中定义/声明了但在主函数和GoBang文件中没申明导致用不了，我想要将声明直接挪进GoBangMaster.cpp和main.cpp中，但发现GoBang在GoBang中有过定义了，请问您的代码想要在编译器上运行要做哪些改动呢？

**Comment by yfismine** [comment]
全部代码都同步在项目中了，有两个入口文件Main.cpp和NewMain.cpp,前者是大一的时候写的，后者是后来重新看时感觉性能上可以有优化重新更新了一下

**Comment by Fooler00** [comment]
![image](https://github.com/yfismine/GoBang-AI/assets/144091962/b68ae48f-6703-4fae-a16e-f7989e27be9c)
zhuh主函数中悔棋函数报错

**Comment by Fooler00** [comment]
然后算法函数中有很多类型和函数全都报错
![image](https://github.com/yfismine/GoBang-AI/assets/144091962/ab952cc2-da7a-4b48-8473-71d2e318ae38)

**Comment by Fooler00** [comment]
没有在您的代码上做任何修改，直接code download下来的，不知道为啥跑不了，全是报错

**Comment by yfismine** [comment]
看样子像是编译器检索的原文件路径没有弄好，可以把项目根文件设置为资源文件，让编译器进行检索
